### ISSUE TITLE
Improve the checkbox

### ISSUE THREAD

**Issue by thefuxia** [wpsitecare/wp-featherlight#24]
There are a couple of minor issues with the current state of the deactivation checkbox:
1. It is placed way down on the right metabox column. Hard to find.
2. It has a title that shouldn't be there: a normal author shouldn't have to know anything about the name of the plugin. On the other hand, using just _Lightbox_ as metabox title seems to be redundant.
3. You have to _activate_ the checkbox to _deactivate_ the feature. This is odd.

How about putting the checkbox into the _Publish box_ (hook: `post_submitbox_misc_actions`) and setting it to activated by default with a label _Lightbox active_?

This would solve all these issues with very little code change.

**Comment by robneu** [comment]
I'm not sure if it's worth reversing the checkbox state for this at this point. We're up to 9,000 active installs and changing it now seems like it'd probably just be confusing. I do like removing the extra meta box in favor of putting the checkbox in the publish box, so I've gone ahead and done that.

Any thoughts/opinions on whether it's worth it to reverse the checkbox to be checked when active rather than checked to deactivate? If I were starting from scratch, I'd definitely switch it, I just don't want to confuse people who are already used to it working the other way.
