### ISSUE TITLE
Will it work together with RICG Responsive Images?

### ISSUE THREAD

**Issue by mateoserendipia** [wpsitecare/wp-featherlight#26]
Hi,

I'm not sure if this type of question should be asked here, but I didn't find any other forum, so I thought I'd just try. 

I've installed wp- featherlight today, and are very happy with it, it works very well! I also installed RICG Responsive Images, in an attempt to regulate the 'weight' of images that are served to small screens (such as mobile phones). Both plugins work fine, all thumbnails are light boxed by featherlight, and when not clicked on, are dynamically served (so large on large screens, smaller on mobile screens). But when checking and testing in Chrome (developers view), I noticed that an image that is opened in a (featherlight) lightbox is back to the original size, even on small mobile screens. This means that the effect of RICG Responsive Images (serving smaller native images according to screen size) is gone. Is this correct, or am I doing something wrong?

Thanks!

**Comment by robneu** [comment]
Hey there,

WP Featherlight doesn't alter the way WordPress galleries and images are embedded, so the issue you're describing would be related to WordPress core. 

The thumbnail version of the images sounds like it's working correctly, but when WordPress links to the "media file" it links to the full, un-cropped image. This is the image that is lightboxed by WP Featherlight.

In order to work around this, you would need to change how WordPress is handling the image and gallery embeds. [This thread](http://wordpress.stackexchange.com/questions/3523/link-to-large-image-version-instead-of-original) has some more information about how the images could be filtered.

I think this is probably outside of the scope of WP Featherlight, but it might be worth [opening an issue](https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues) with RICG Responsive Images because that plugin is likely going to be merged into WordPress core at some point. I think it would be a good thing to provide more control over image embeds for different device sizes.

**Comment by mateoserendipia** [comment]
Hi,
Thanks for the very prompt answer (on a sunday!), and for the link to the thread - I'll dive into that, and I'll open an issue with RIGC Responsive!
Thanks again,Thies
----- Oorspronkelijk bericht -----
Van: Robert Neu notifications@github.com
Aan: wpsitecare/wp-featherlight wp-featherlight@noreply.github.com
Cc: mateoserendipia thiesdewaard@online.nl
Verzonden: Sun, 27 Sep 2015 23:02:44 +0200 (CEST)
Onderwerp: Re: [wp-featherlight] Will it work together with RICG Responsive Images? (#26)

Hey there,WP Featherlight doesn't alter the way WordPress galleries and images are embedded, so the issue you're describing would be related to WordPress core.The thumbnail version of the images sounds like it's working correctly, but when WordPress links to the "media file" it links to the full, un-cropped image. This is the image that is lightboxed by WP Featherlight.In order to work around this, you would need to change how WordPress is handling the image and gallery embeds. This thread has some more information about how the images could be filtered.I think this is probably outside of the scope of WP Featherlight, but it might be worth opening an issue with RICG Responsive Images because that plugin is likely going to be merged into WordPress core at some point and I think it would be a good thing to provide more control over image embeds for different device sizes.—

**Comment by mateoserendipia** [comment]
Hi Robert, the issue is now being further discussed at the RICG forum, here:
https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/189

Cheers!

**Comment by robneu** [comment]
:+1: I'm going to close this out for now.
