### ISSUE TITLE
CSS optionally included in the footer

### ISSUE THREAD

**Issue by primozcigler** [wpsitecare/wp-featherlight#30]
Hi there,

This time I will rather ask first and implement later :smiley: 

I would like to have the CSS of featherlight be included in the wp foot instead of head.

The reason? Prioritization of critical rendering path. The lightbox CSS will practically never be needed when the site first loads, so it is not critical to include this CSS in the `<head>`. It would make sense therefore, to include it at the end of HTML document (or at least give an option via filter).

I see two possible implementations:
1. Switch to the footer by default.
   
   PROS: it will be smarter default for great majority of users. No extra work needed.
   CONS: might break for themes which do use `wp_head()` but no `wp_foot()`. Potentially breaking backwards-compat.
2. Provide a filter to give the theme/plugin authors to opt-in for CSS loaded in footer.
   
   PROS: everything stays the same for the current users.
   CONS: this is worse default out of two. Probably only a small fraction of the theme developers will opt-in for this.

Implementation: `wp_enqueue_style` hooked to the `wp_foot`. I did it already, works great (from [WP 3.3](https://codex.wordpress.org/Function_Reference/wp_enqueue_style#Change_Log)).

Please discuss and I can prepare the PR.

**Comment by robneu** [comment]
Hey Primo,

Hmm... I don't think we'd really have to worry too much about breaking sites. If a theme is missing the `wp_footer` function our plugin is probably non-functional as it is because we load our JS there. I actually ran into this on a support ticket recently and not having `wp_footer` in the theme will definitely break the output as it is right now.

I think we should still register the scripts on the correct hook and then just enqueue them in the footer. I'm pretty sure they should get picked up by [print_late_styles](https://developer.wordpress.org/reference/functions/print_late_styles/).

The only other concern I have here is validation. Unless the HTML5 spec is different in this area, any external stylesheet loaded outside of the `<head>` is considered invalid. :\

**Comment by robneu** [comment]
I did think of one other back-compat issue. Anyone declaring custom styles in their theme could find that the plugin styles are overriding what they didn't previously due to the cascade. 

This probably won't be that big of a deal as plugin styles are typically loaded after the main stylesheet anyway, but some people may have purposely loaded their theme after the plugin to avoid having to make their CSS overly specific.

I kind of doubt this is really common, but I've been surprised about things like this in the past...

**Comment by primozcigler** [comment]
Hi,

> Hmm... I don't think we'd really have to worry too much about breaking sites.

Great. Let's go directly then. Though I would still add a filter which allows you to override this behavior and put styles back to head. One more boolean filter for this cannot hurt.

> I think we should still register the scripts on the correct hook and then just enqueue them in the footer. I'm pretty sure they should get picked up by print_late_styles.

Absolutely. I agree.

> The only other concern I have here is validation. Unless the HTML5 spec is different in this area, any external stylesheet loaded outside of the <head> is considered invalid. :\

The HTML5 allows the `<link>` elements in `<body>` as well, as long as they have the required `property` attribute. We could fix this as well, but actually that should be fixed in the WP core (adding `property="stylesheet"` to all the stylesheets in the footer).

> I did think of one other back-compat issue. Anyone declaring custom styles in their theme could find that the plugin styles are overriding what they didn't previously due to the cascade.

You can always win (and it is also more reliable) with the selectors specificity. Alternatively I am prepared to add short instructions in README how to add your own CSS after the plugin's CSS loaded in the footer.

**Comment by robneu** [comment]
Awesome! If you want to throw together a PR for this, I'll take a look and merge it in.

The `<link>` element thing sounds like it might be a good candidate for a core patch if you're into dealing with Trac and all that mess.

**Comment by primozcigler** [comment]
Hi Rob!

I will make a PR the next week.

> if you're into dealing with Trac and all that mess.

Not my favorite thing to do, but I'll see :smiley:
