### ISSUE TITLE
WebP Support?

### ISSUE THREAD

**Issue by leepeterson** [wpsitecare/wp-featherlight#36]
Any plans on introducing WebP support? Was considering forking and adding it myself. Seems [line 19 of wpFeatherlight.js](https://github.com/wpsitecare/wp-featherlight/blob/develop/assets/plugin/js/wpFeatherlight.js#L19) needs webp added to the regex and that'd be it, though I haven't looked through the entire code base yet.

**Comment by robneu** [comment]
Hey Lee,

There are currently no plans to add WebP support for the reasons outlined in [this ticket](https://wordpress.org/support/topic/webp-images-no-lightbox/). Of course you are free to fork the plugin and add it if you like and we'll consider making the change if core ever allows it as a default image format.

**Comment by leepeterson** [comment]
Thanks for pointing me to that support ticket. Hadn't considered looking there. It's logical not to add it to the plugin considering it very well may become an abandoned project. But how about making formats hookable? Might be asking a lot, I know, but only a thought.

**Comment by cessez-le-feu** [comment]
Hello,

I think you should reconsider this ticket. It was closed for the reason that, at the time, WordPress core didn’t allow WebP by default. However, the situation has changed since. See:

- WordPress 5.8 adds WebP support
https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/

And actually, updating the "wp-featherlight" plugin to support WebP is a child’s game. I literally just replaced all occurrences of "bmp" with "webp" in the plugin’s code, and it worked!
