### ISSUE TITLE
image descriptions as captions

### ISSUE THREAD

**Issue by stephansch321** [wpsitecare/wp-featherlight#39]
Hello,
I would like to display the descriptions of the used images as the caption in the featherlight lightbox view. Is there a way how I could customize your plugin to achieve this? If you consider this as useful for others, you could perhaps extend the filter setting for wp_featherlight_captions.

kind regards
stephan

**Comment by robneu** [comment]
I'm not quite sure I understand what you're asking. Do you mean alt text?

**Comment by stephansch321** [comment]
sorry, not the alt text, but the conten of the description field:
![screenshot](https://user-images.githubusercontent.com/13422508/31586338-b28204b6-b1cf-11e7-94e5-ef7c3661d043.jpg)

**Comment by dani-snippets** [comment]
this is already some months ago - concerning some text to display with an image.
the caption is only displayed when a wp body_class() is existing in the wp-theme. 

The wp-featherlight uses the body_class exactly only for the one reason to show captions or not. And this is what does not suit for me, because the wp body class is overloaded and the wp-featherlight is a featherlight plugin. 

My question is: would it be possible in the plugin - to solve the "display caption true or false function" in another way. Not via the wp_body_class. If it is possible to click the lightbox function off per page, it should be also easily possible to click the caption off. 
That would be great.

Great Plugin!

**Comment by ryandonsullivan** [comment]
Thanks @lubeca. We'll take that into consideration in a future update. But this isn't something we'll be addressing in the immediate future since using wp_body_class is a primary component for making this plugin compatible with _most_ WordPress themes.
